### ISSUE TITLE
想看一看，环境弄了许久也没成功

### ISSUE THREAD

**Issue by qiushanjun** [Gengzigang/PCT#6]
Traceback (most recent call last):
  File "./tools/train.py", line 15, in <module>
    from mmpose.apis import train_model
  File "/root/miniconda3/lib/python3.8/site-packages/mmpose/apis/__init__.py", line 2, in <module>
    from .inference import (collect_multi_frames, inference_bottom_up_pose_model,
  File "/root/miniconda3/lib/python3.8/site-packages/mmpose/apis/inference.py", line 17, in <module>
    from mmpose.datasets.dataset_info import DatasetInfo
  File "/root/miniconda3/lib/python3.8/site-packages/mmpose/datasets/__init__.py", line 7, in <module>
    from .datasets import (  # isort:skip
  File "/root/miniconda3/lib/python3.8/site-packages/mmpose/datasets/datasets/__init__.py", line 2, in <module>
    from ...deprecated import (TopDownFreiHandDataset, TopDownOneHand10KDataset,
  File "/root/miniconda3/lib/python3.8/site-packages/mmpose/deprecated.py", line 5, in <module>
    from .datasets.datasets.base import Kpt2dSviewRgbImgTopDownDataset
  File "/root/miniconda3/lib/python3.8/site-packages/mmpose/datasets/datasets/base/__init__.py", line 2, in <module>
    from .kpt_2d_sview_rgb_img_bottom_up_dataset import \
  File "/root/miniconda3/lib/python3.8/site-packages/mmpose/datasets/datasets/base/kpt_2d_sview_rgb_img_bottom_up_dataset.py", line 8, in <module>
    from xtcocotools.coco import COCO
  File "/root/miniconda3/lib/python3.8/site-packages/xtcocotools/coco.py", line 58, in <module>
    from . import mask as maskUtils
  File "/root/miniconda3/lib/python3.8/site-packages/xtcocotools/mask.py", line 3, in <module>
    import xtcocotools._mask as _mask
  File "xtcocotools/_mask.pyx", line 1, in init xtcocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

**Comment by Gengzigang** [comment]
You can try "pip install numpy --upgrade".
